name: 'Build for Windows'
description: 'Creates a Windows build'
inputs:
  BUILD_CONFIG:
    required: true
    description: 'Build configuration, e.g., Release'
  BUILD_ARCHITECTURE:
    required: true
    description: 'Build architecture, e.g., x64'
ouputs:
defaults:
  run:
    shell: pwsh
runs:
  using: "composite"
  steps:  
    - uses: actions/checkout@v4
      name: Checkout
    - uses: actions/setup-dotnet@v4
      name: Set up dotnet
      with: 
        global-json-file: global.json
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - run: dotnet restore --locked-mode
      name: Restore packages
      shell: pwsh
    - run: dotnet build ${{github.workspace}}/PrintTool/PrintTool.csproj --no-restore -c ${{ inputs.BUILD_CONFIG }} -a ${{ inputs.BUILD_ARCHITECTURE }}
      name: Build project for release      
      shell: pwsh
    - run: dotnet build ${{github.workspace}}/PrintTool.UnitTests/PrintTool.UnitTests.csproj --no-restore -c ${{ inputs.BUILD_CONFIG }} -a ${{ inputs.BUILD_ARCHITECTURE }}
      name: Build test project
      shell: pwsh
    - run: dotnet test ${{github.workspace}}/PrintTool.UnitTests/PrintTool.UnitTests.csproj --no-restore -c ${{ inputs.BUILD_CONFIG }} -a ${{ inputs.BUILD_ARCHITECTURE }}
      name: Run unit tests
      shell: pwsh
    - run: dotnet publish ${{github.workspace}}/PrintTool/PrintTool.csproj -a ${{ inputs.BUILD_ARCHITECTURE }} --output ${{github.workspace}}/artifacts/PrintToolWindows --no-restore -c ${{ inputs.BUILD_CONFIG }}
      name: Publish project and upload to artifact
      shell: pwsh
    - uses: actions/upload-artifact@v4
      with:
        name: PrintToolWindows
        path: '${{github.workspace}}/artifacts/PrintToolWindows'
